import C from 'lib/constants';

export default[
  {
    title: '专业版',
    description: '',
    plan: C.TEAMPLAN.PRO,
    product_no: C.PRODUCT_NO.PLAN,
    product_id: C.TEAMPLAN.PRO.toUpperCase() + '_' + C.PRODUCT_NO.PLAN,
    original_price: '9900',
    discount: [],
    version: 0,
    amount_min: null,
    amount_max: null,
    stock_total: null,
    stock_current: null,
    date_create: new Date(),
    date_update: new Date(),
  },
  {
    title: '企业版',
    description: '',
    plan: C.TEAMPLAN.ENT,
    product_no: C.PRODUCT_NO.PLAN,
    product_id: C.TEAMPLAN.ENT.toUpperCase() + '_' + C.PRODUCT_NO.PLAN,
    original_price: '19900',
    discount: [],
    version: 0,
    amount_min: null,
    amount_max: null,
    stock_total: null,
    stock_current: null,
    date_create: new Date(),
    date_update: new Date(),
  },
  {
    title: '专业版人数续费',
    description: '',
    plan: C.TEAMPLAN.PRO,
    product_no: C.PRODUCT_NO.MEMBER,
    product_id: C.TEAMPLAN.PRO.toUpperCase() + '_' + C.PRODUCT_NO.MEMBER,
    original_price: '990',
    discount: [],
    version: 0,
    amount_min: null,
    amount_max: null,
    stock_total: null,
    stock_current: null,
    date_create: new Date(),
    date_update: new Date(),
  },
  {
    title: '企业版人数续费',
    description: '',
    plan: C.TEAMPLAN.ENT,
    product_no: C.PRODUCT_NO.MEMBER,
    product_id: C.TEAMPLAN.ENT.toUpperCase() + '_' + C.PRODUCT_NO.MEMBER,
    original_price: '1990',
    discount: [],
    version: 0,
    amount_min: null,
    amount_max: null,
    stock_total: null,
    stock_current: null,
    date_create: new Date(),
    date_update: new Date(),
  },
];
