import C, { ENUMS } from 'lib/constants';

export let validation = {
  creator: { $objectId: 1 },
  action: { $enum: ENUMS.ACTIVITY_ACTION },
  target_type: { $enum: ENUMS.OBJECT_TYPE },
  app: { $objectId: 1, optional: true },
  company: { $objectId: 1, optional: true },
  company_id: { $objectId: 1, optional: true },
  project: { $objectId: 1, optional: true },
  project_discussion: { type: 'object', optional: true },
  project_member: { optional: true },
  company_member: { type: 'object', optional: true },
  task: { $objectId: 1, optional: true },
  ori_task: { type: 'object', optional: true },
  user: { $objectId: 1, optional: true },
  tag: { type: 'object', optional: true },
  approval_item: { $objectId: 1, optional: true },
  approval_template: { $objectId: 1, optional: true },
  document_dir: { type: ['object', 'array'], optional: true },
  document_file: { type: ['object', 'array'], optional: true },
  document_path: { type: ['object', 'array'], optional: true },
  original_dir: { type: 'object', optional: true },
  dest_dir: { type: 'object', optional: true },
  announcement: { $objectId: 1, optional: true },
  announcement_draft: { $objectId: 1, optional: true },
  schedule: { type: 'object', optional: true },
  request: { $objectId: 1, optional: true },
  field: { type: 'object', optional: true },
  update_fields: { type: 'array', optional: true },
  date_create: { type: 'date' },
  sign_record: { type: 'object', optional: true },
  position: { type: 'object', optional: true },
};
